version: "3.8"
services:
  rapor:
    container_name: rapor
    build:
      dockerfile: Dockerfile
      context: .
    image: rapor
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3002"
