version: "3.8"
services:
  development:
    container_name: development
    build:
      context: . #if your Dockerfile is not at the same level change the path here (./frontend)
      target: dev
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - letsencrypt-docker-compose_default
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - letsencrypt-docker-compose_default
# change port in prod ex: 5432:5432 to 5432 only
# enable this in prod
networks:
  letsencrypt-docker-compose_default:
    # external: true
