"use server";
import prisma from "@/db";

export async function insertAllMuridData() {
  return await prisma.murid.createMany({
    data: [
      {
        namaIndo: "Abdullah Fabanyo",
        namaArab: "عبد الله فبانيو",
        kelas: "Abdullah",
        induk: 23240404,
      },
      {
        namaIndo: "Affan Muadz Alfarisi",
        namaArab: "عفان معاذ الفارسي",
        kelas: "Abdullah",
        induk: 23240381,
      },
      {
        namaIndo: "Ahmad Syafi'I Ali Naja",
        namaArab: "أحمد شافعي علي نجا",
        kelas: "Abdullah",
        induk: 23240382,
      },
      {
        namaIndo: "Aksara Disastra Aindukirahman",
        namaArab: "أكسارا ديساسترا أيدي رحمن",
        kelas: "Abdullah",
        induk: 23240384,
      },
      {
        namaIndo: "Ammar Zuhdi Ramadhan",
        namaArab: "عمار زهدي رمضان",
        kelas: "Abdullah",
        induk: 23240405,
      },
      {
        namaIndo: "Azhar Muwaffaq Rasyinduk",
        namaArab: "أزهر موفق رشيد",
        kelas: "Abdullah",
        induk: 23240406,
      },
      {
        namaIndo: "Fahrezi Azka Ghifari",
        namaArab: "فحرازي أزكى غفاري ",
        kelas: "Abdullah",
        induk: 23240390,
      },
      {
        namaIndo: "Fatih Tsabit Fadhlurrohman",
        namaArab: "فاتح ثابت فضل الرحمن",
        kelas: "Abdullah",
        induk: 23240391,
      },
      {
        namaIndo: "Ghifarino Axl Luqman Adiguna",
        namaArab: "غيفارنو أكسيل لقمان أديغونا",
        kelas: "Abdullah",
        induk: 23240413,
      },
      {
        namaIndo: "Hadfiy Zahinduk El Kayyis",
        namaArab: "هدفي زاهد الكيس",
        kelas: "Abdullah",
        induk: 23240393,
      },
      {
        namaIndo: "Hafy Ibrahim Alafa",
        namaArab: "هافي ابراهيم آلافا",
        kelas: "Abdullah",
        induk: 23240394,
      },
      {
        namaIndo: "Muhammad Al Rafif Santoso",
        namaArab: "محمد الررفيف سانتوسو",
        kelas: "Abdullah",
        induk: 23240395,
      },
      {
        namaIndo: "Muhammad Ali Zubair",
        namaArab: "محمدعلي زبير",
        kelas: "Abdullah",
        induk: 23240408,
      },
      {
        namaIndo: "Muhammad Fatih Abqori",
        namaArab: "محمد فاتح عبقري",
        kelas: "Abdullah",
        induk: 23240414,
      },
      {
        namaIndo: "Muhammad Hanif Musyaffa",
        namaArab: "محمد حنيف مشفى",
        kelas: "Abdullah",
        induk: 23240397,
      },
      {
        namaIndo: "Muhammad Isrofil Islamadina",
        namaArab: "محمد إسرافيل إسلام دينا",
        kelas: "Abdullah",
        induk: 23240398,
      },
      {
        namaIndo: "Muhammad Rafka Zafran",
        namaArab: "محمد رافكا زفران",
        kelas: "Abdullah",
        induk: 23240399,
      },
      {
        namaIndo: "Muhammad Shalih Al Utsaimin",
        namaArab: "محمد صالح العثيمن",
        kelas: "Abdullah",
        induk: 23240400,
      },
      {
        namaIndo: "Salman Alfarisi Araya",
        namaArab: "سلمان الفارسي آرايا",
        kelas: "Abdullah",
        induk: 22230356,
      },
      {
        namaIndo: "Aisha Hamna",
        namaArab: "عائشة حمنى",
        kelas: "Aisyah",
        induk: 23240383,
      },
      {
        namaIndo: "Annisa Ayu Setya",
        namaArab: "النساء آيو ساتيا",
        kelas: "Aisyah",
        induk: 23240385,
      },
      {
        namaIndo: "Asiya Fahad Alamudy",
        namaArab: "أسية فهد العمودي",
        kelas: "Aisyah",
        induk: 23240386,
      },
      {
        namaIndo: "Assyifa Qiana Furqon",
        namaArab: "الشفاء قيانا فرقان",
        kelas: "Aisyah",
        induk: 23240415,
      },
      {
        namaIndo: "Astrinduk Sukma Artami",
        namaArab: "آستريد سوكما أرتامي",
        kelas: "Aisyah",
        induk: 23240387,
      },
      {
        namaIndo: "Azkiya Nurul Qur'Ani",
        namaArab: "أذكياء نور القرآن",
        kelas: "Aisyah",
        induk: 23240412,
      },
      {
        namaIndo: "Baiq Aisha Zahra Khalisa",
        namaArab: "بائق عائشة زهر خالصا",
        kelas: "Aisyah",
        induk: 23240388,
      },
      {
        namaIndo: "Eirlys Zikra Bordyoga",
        namaArab: "أيرليس ذكرا بورديوغا",
        kelas: "Aisyah",
        induk: 23240389,
      },
      {
        namaIndo: "Fildzah Janeeta Syarafana",
        namaArab: "فيلزة جانيتا شرفنا",
        kelas: "Aisyah",
        induk: 23240392,
      },
      {
        namaIndo: "Kinara Zahsy Prawiradilaga",
        namaArab: "كينارا زحشي براويراديلاغا",
        kelas: "Aisyah",
        induk: 23240407,
      },
      {
        namaIndo: "Mutiah Ayudia Inara",
        namaArab: "مطيعة آيوديا إينارا",
        kelas: "Aisyah",
        induk: 23240416,
      },
      {
        namaIndo: "Naisya Zaina Rizqiana",
        namaArab: "نيشا زينا رزقنا",
        kelas: "Aisyah",
        induk: 23240401,
      },
      {
        namaIndo: "Shanindya El-Qisthi",
        namaArab: "سانينديا القسطي",
        kelas: "Aisyah",
        induk: 23240403,
      },
      {
        namaIndo: "Shabira Annisa Hamdani",
        namaArab: "صابرة النساء حمدان",
        kelas: "Aisyah",
        induk: 23240417,
      },
      {
        namaIndo: "Adila Nisa Ardani",
        namaArab: "عادلة نساء أرداني",
        kelas: "Fathimah",
        induk: 22230348,
      },
      {
        namaIndo: "Anandita Ratu Evelyn",
        namaArab: "أنانديتا راتو إيفلين",
        kelas: "Fathimah",
        induk: 22230317,
      },
      {
        namaIndo: "Avicena Ceisya Asadel",
        namaArab: "فيتشينا تشيشا أساديل",
        kelas: "Fathimah",
        induk: 22230319,
      },
      {
        namaIndo: "Bernice Mahreennisa Raqiyya",
        namaArab: "برنيش مهر النساء رقيا",
        kelas: "Fathimah",
        induk: 22230367,
      },
      {
        namaIndo: "Jihan Makailah Fakhira Khusuf",
        namaArab: "جيهان مكايلة فخيرة خسوف",
        kelas: "Fathimah",
        induk: 22230363,
      },
      {
        namaIndo: "Kalisya Armayra Muqaddar",
        namaArab: "كاليشا أرمايرا مقدر",
        kelas: "Fathimah",
        induk: 22230351,
      },
      {
        namaIndo: "Nayyara Khairunnisa Hakim",
        namaArab: "نيارة خير النساء حكيم",
        kelas: "Fathimah",
        induk: 22230355,
      },
      {
        namaIndo: "Raihana Izzatunnisa Marsya",
        namaArab: "ريحانة عزة النساء مارشا",
        kelas: "Fathimah",
        induk: 22230366,
      },
      {
        namaIndo: "Adilla Nindukaan Khofia",
        namaArab: "عادلة نداء خفيا",
        kelas: "Khadijah",
        induk: 22230311,
      },
      {
        namaIndo: "Aisyah Alya Lathifa",
        namaArab: "عائشة علياء لطيفة",
        kelas: "Khadijah",
        induk: 22230314,
      },
      {
        namaIndo: "Aisyah Rayya Almahyra",
        namaArab: "عائشة ريا المهيرة",
        kelas: "Khadijah",
        induk: 22230315,
      },
      {
        namaIndo: "Alesha Khaira Dzakira",
        namaArab: "أليشا خيرا ذكيرا",
        kelas: "Khadijah",
        induk: 22230316,
      },
      {
        namaIndo: "Aya Sofia Al-qudsiyyah",
        namaArab: "آيا صفية القدسية",
        kelas: "Khadijah",
        induk: 22230362,
      },
      {
        namaIndo: "Gasha Mazaya",
        namaArab: " غاشا مزايا",
        kelas: "Khadijah",
        induk: 22230325,
      },
      {
        namaIndo: "Kameela Queency Ramond",
        namaArab: "كميلا كوينتشي راموند",
        kelas: "Khadijah",
        induk: 22230377,
      },
      {
        namaIndo: "Zahra Ashima Dinillah",
        namaArab: "زهرة عاصمة دين الله",
        kelas: "Khadijah",
        induk: 22230340,
      },
      {
        namaIndo: "Abdurrahman Rainduk",
        namaArab: "عبد الرحمن رائد",
        kelas: "Ubay",
        induk: 22230374,
      },
      {
        namaIndo: "Ahmad Aufa Abqory",
        namaArab: "أحمد أوفى عبقري",
        kelas: "Ubay",
        induk: 22230312,
      },
      {
        namaIndo: "Andi Muhammad Ammar Athaya",
        namaArab: "أندي محمد عمار عطايا",
        kelas: "Ubay",
        induk: 22230360,
      },
      {
        namaIndo: "Atha Muhammad Alfarazky",
        namaArab: "أتا محمد ألفاريزقي",
        kelas: "Ubay",
        induk: 22230361,
      },
      {
        namaIndo: "Faizan Arasy Rasydan",
        namaArab: "فائزان عراسي راشدان",
        kelas: "Ubay",
        induk: 22230323,
      },
      {
        namaIndo: "Faza Ibrahim Al Kafil",
        namaArab: "فازا إبراهيم الكافل",
        kelas: "Ubay",
        induk: 22230324,
      },
      {
        namaIndo: "Gaza Abrar Alfathir",
        namaArab: "غزا أبرار الفاطر",
        kelas: "Ubay",
        induk: 22230326,
      },
      {
        namaIndo: "Lingga Wijaksana Purawinata",
        namaArab: "لينجا ويجاكسانا بوراويناتا",
        kelas: "Ubay",
        induk: 22230352,
      },
      {
        namaIndo: "Muhammad Ersalan Ambadar",
        namaArab: "محمد إرسلان أمبادر",
        kelas: "Ubay",
        induk: 22230369,
      },
      {
        namaIndo: "Muhammad Thaariq Mardiyanto",
        namaArab: "محمد طارق مرديانتو",
        kelas: "Ubay",
        induk: 22230354,
      },
      {
        namaIndo: "Rayi Raynala Zefa",
        namaArab: "راي رينالا زيفا",
        kelas: "Ubay",
        induk: 22230336,
      },
      {
        namaIndo: "Zeit Pramudia Wijatmiko",
        namaArab: "زيت براموديا ويجاتميكو",
        kelas: "Ubay",
        induk: 22230372,
      },
      {
        namaIndo: "Airlangga Agung Nurzaki",
        namaArab: "أيرلانجا أجونج نورزاكي",
        kelas: "Utsman",
        induk: 22230313,
      },
      {
        namaIndo: "Arrasya Firas Alghifari",
        namaArab: "أراشا فراس الغفاري",
        kelas: "Utsman",
        induk: 22230318,
      },
      {
        namaIndo: "Arshaka Uwais Al Qarni",
        namaArab: "أرشكا أويس القرني",
        kelas: "Utsman",
        induk: 22230375,
      },
      {
        namaIndo: "Dzikri Khadafi Hamizan",
        namaArab: "ذكري القذافي حميزان",
        kelas: "Utsman",
        induk: 22230322,
      },
      {
        namaIndo: "Gaza Al Qassam Amrullah",
        namaArab: "غزا القسام أمر الله",
        kelas: "Utsman",
        induk: 22230327,
      },
      {
        namaIndo: "Ibrahim Assamy",
        namaArab: "إبراهيم السامي",
        kelas: "Utsman",
        induk: 22230328,
      },
      {
        namaIndo: "Muhammad Atharrazka Alfatih",
        namaArab: "محمد أتارازكا الفاتح",
        kelas: "Utsman",
        induk: 22230331,
      },
      {
        namaIndo: "Muhammad Fauzan Karim",
        namaArab: "محمد فزان كريم",
        kelas: "Utsman",
        induk: 22230368,
      },
      {
        namaIndo: "Muhammad Mikail Islamadina",
        namaArab: "محمد ميكائيل إسلامادينا",
        kelas: "Utsman",
        induk: 22230353,
      },
      {
        namaIndo: "Muhammad Shindukdiq Aulia",
        namaArab: "محمد صديق أولياء",
        kelas: "Utsman",
        induk: 22230365,
      },
      {
        namaIndo: "Muhammad Zhafran Abdad",
        namaArab: "محمد ظفران عبداد",
        kelas: "Utsman",
        induk: 22230333,
      },
      {
        namaIndo: "Salman Shalahuddin Muhammad",
        namaArab: "سلمان صلاح الدين محمد",
        kelas: "Utsman",
        induk: 22230337,
      },
      {
        namaIndo: "Akmal Afnan Hakim",
        namaArab: "أكمال أفنان حكيم",
        kelas: "Abu Bakr",
        induk: 21220250,
      },
      {
        namaIndo: "Barra Haindukar",
        namaArab: "براء حيدر",
        kelas: "Abu Bakr",
        induk: 21220281,
      },
      {
        namaIndo: "Darris Alibani Safar",
        kelas: "Abu Bakr",
        induk: 21220260,
      },
      {
        namaIndo: "Hanif Ghazali Alafa",
        kelas: "Abu Bakr",
        induk: 21220269,
      },
      {
        namaIndo: "Maliq Aliyandro Ramond",
        kelas: "Abu Bakr",
        induk: 22230376,
      },
      {
        namaIndo: "Muhammad Asad Al-faqih",
        kelas: "Abu Bakr",
        induk: 21220277,
      },
      {
        namaIndo: "Muhammad Raef Bathlathun El Bashil",
        kelas: "Abu Bakr",
        induk: 21220279,
      },
      {
        namaIndo: "Muhammad Uwais Abdurrahman",
        kelas: "Abu Bakr",
        induk: 21220282,
      },
      {
        namaIndo: "Reinanda Hamizan Adinata",
        kelas: "Abu Bakr",
        induk: 21220289,
      },
      {
        namaIndo: "Sufyan Ats-tsauri",
        kelas: "Abu Bakr",
        induk: 21220292,
      },
      {
        namaIndo: "Tristiyan Abiy Pratama",
        kelas: "Abu Bakr",
        induk: 21220294,
      },
      {
        namaIndo: "Abrar Osama Gareeba",
        namaArab: "أبرار أسامة غريبة",
        kelas: "Shafiyyah",
        induk: 21220265,
      },
      {
        namaIndo: "Adzkia Hasna Sakhi",
        namaArab: "أزكياء حسناء ساخي",
        kelas: "Shafiyyah",
        induk: 21220246,
      },
      {
        namaIndo: "Aisyah Khanza Putrialifya",
        namaArab: "عائشة خنزاء بوترياليفيا",
        kelas: "Shafiyyah",
        induk: 21220248,
      },
      {
        namaIndo: "Alika Zaviera Sava",
        namaArab: " أليكا زافيرا شافا",
        kelas: "Shafiyyah",
        induk: 21220252,
      },
      {
        namaIndo: "Assyabiya Rafifa Santoso",
        namaArab: "آشبيا رفيفة سانتوسو",
        kelas: "Shafiyyah",
        induk: 21220254,
      },
      {
        namaIndo: "Azumi Isaura Hanza",
        namaArab: "أزومي إساورا حنزاء",
        kelas: "Shafiyyah",
        induk: 21220257,
      },
      {
        namaIndo: "Fatiha Shea Majinduk",
        namaArab: "فاتحة شيه مجيد",
        kelas: "Shafiyyah",
        induk: 21220264,
      },
      {
        namaIndo: "Gemmarosa Larasati",
        namaArab: "جيماروسا لاراساتي",
        kelas: "Shafiyyah",
        induk: 21220266,
      },
      {
        namaIndo: "Khodijah At-thohiroh Maqbul",
        namaArab: "خديجة الطاهرة مقبول ",
        kelas: "Shafiyyah",
        induk: 21220272,
      },
      {
        namaIndo: "Maritza Davina Aretha",
        namaArab: "مريتزا دافينا أريثا",
        kelas: "Shafiyyah",
        induk: 21220275,
      },
      {
        namaIndo: "Nadya Alimah",
        namaArab: "نادية عالمة",
        kelas: "Shafiyyah",
        induk: 21220283,
      },
      {
        namaIndo: "Qathrunnada Earlyta Arsyfa",
        namaArab: "قطر الندى ايرليتا أرسيفا",
        kelas: "Shafiyyah",
        induk: 21220286,
      },
      {
        namaIndo: "Qianna Qalesya Afsheena",
        namaArab: "كيانا كاليسيا أفشينا",
        kelas: "Shafiyyah",
        induk: 21220287,
      },
      {
        namaIndo: "Syazwina Uzma Eryna",
        namaArab: "سازوينا أوزما إيرينا",
        kelas: "Shafiyyah",
        induk: 21220293,
      },
      {
        namaIndo: "Zainab Al Muyassarah",
        namaArab: "زينب الميسرة",
        kelas: "Shafiyyah",
        induk: 21220296,
      },
      {
        namaIndo: "Agha Assyauqi Ramdhani",
        kelas: "Umar",
        induk: 20210202,
      },
      {
        namaIndo: "Althaf Al Fatih Ramadhan",
        kelas: "Umar",
        induk: 21220298,
      },
      {
        namaIndo: "Aufaa Yuta Daniswara",
        kelas: "Umar",
        induk: 21220255,
      },
      {
        namaIndo: "Ayyash Shubhi Abdul Latif",
        kelas: "Umar",
        induk: 21220299,
      },
      {
        namaIndo: "Bilal Al Fatih",
        kelas: "Umar",
        induk: 21220258,
      },
      {
        namaIndo: "Fakhri Faindukhan Zahran",
        kelas: "Umar",
        induk: 21220262,
      },
      {
        namaIndo: "Fatih Mufinduk Windukyanto",
        kelas: "Umar",
        induk: 21220263,
      },
      {
        namaIndo: "Hajjaj Hisyam Alhindawi",
        kelas: "Umar",
        induk: 21220268,
      },
      {
        namaIndo: "Lalu Muhammad Omar Ramadhan",
        kelas: "Umar",
        induk: 21220273,
      },
      {
        namaIndo: "Muhammad Razzan Abhimanyu Prasetiyo",
        kelas: "Umar",
        induk: 21220280,
      },
      {
        namaIndo: "Safaraz Alfatih",
        kelas: "Umar",
        induk: 21220290,
      },
      {
        namaIndo: "Aisha Thurayya Rizkiamira",
        namaArab: " عائشة ثريا ريزكياميرا",
        kelas: "Zainab",
        induk: 21220247,
      },
      {
        namaIndo: "Aisyah Ulinnuha",
        namaArab: "عائشة أولي النهى",
        kelas: "Zainab",
        induk: 21220249,
      },
      {
        namaIndo: "Alexandria Al Khansa",
        namaArab: "أليكسندريا الخنساء",
        kelas: "Zainab",
        induk: 21220251,
      },
      {
        namaIndo: "Annisa Faiha",
        namaArab: "النساء فيحاء",
        kelas: "Zainab",
        induk: 21220253,
      },
      {
        namaIndo: "Btari Devania Sarjono",
        namaArab: "بتاري ديفانيا سارجونو",
        kelas: "zainab",
        induk: 21220259,
      },
      {
        namaIndo: "Eleanor Bryna Salsabila",
        namaArab: "اليانور برينا سلسبيلا",
        kelas: "zainab",
        induk: 21220261,
      },
      {
        namaIndo: "Hayfa Atthahira Malay",
        namaArab: "هيفاء الطاهرة مالاي",
        kelas: "zainab",
        induk: 21220270,
      },
      {
        namaIndo: "Khadega Waleed Obainduk Adam Hamna",
        namaArab: "خديجة وليد ",
        kelas: "zainab",
        induk: 22230417,
      },
      {
        namaIndo: "Khansameyya Sydney Manggala",
        namaArab: "خنساميا سيدني مانجالا",
        kelas: "zainab",
        induk: 21220271,
      },
      {
        namaIndo: "Malika Misha Hanania",
        namaArab: " مليكة ميشا هنانيا",
        kelas: "zainab",
        induk: 21220274,
      },
      {
        namaIndo: "Meisya Kamila Amini",
        namaArab: "ميشا كاميلا أميني",
        kelas: "zainab",
        induk: 21220276,
      },
      {
        namaIndo: "Najwa Az Zahra",
        namaArab: "نجوى الزهرة",
        kelas: "zainab",
        induk: 21220284,
      },
      {
        namaIndo: "Nayla Hanania Fahinduka",
        namaArab: "نيلا هنانيا فهيدة",
        kelas: "zainab",
        induk: 21220285,
      },
      {
        namaIndo: "Shafiyyah Syarif",
        namaArab: "صفية شريف     ",
        kelas: "Zainab",
        induk: 21220291,
      },
      {
        namaIndo: "Zahindukatul Husna Zuljazmy Syafie",
        namaArab: "زهيدة الحسنى زولجسمي شافي ",
        kelas: "Zainab",
        induk: 21220295,
      },
      {
        namaIndo: "Athalla Zain Al Khalifi",
        kelas: "Ali",
        induk: 20210206,
      },
      {
        namaIndo: "Faaza Muhammad Fath",
        kelas: "Ali",
        induk: 20210213,
      },
      {
        namaIndo: "Kenzio Atalarik Radjawane",
        kelas: "Ali",
        induk: 20210219,
      },
      {
        namaIndo: "Muhammad Arshavin Muqaddar",
        kelas: "Ali",
        induk: 20210225,
      },
      {
        namaIndo: "Muhammad Azka Hawnan Al Asyraf",
        kelas: "Ali",
        induk: 20210226,
      },
      {
        namaIndo: "Muhammad Husni Mubarok",
        kelas: "Ali",
        induk: 20210229,
      },
      {
        namaIndo: "Muhammad Muazzam Muslim",
        kelas: "Ali",
        induk: 20210230,
      },
      {
        namaIndo: "Muhammad Rafa Hisyam Prakosa",
        kelas: "Ali",
        induk: 20210232,
      },
      {
        namaIndo: "Muhammad Satria Anjanah",
        kelas: "Ali",
        induk: 20210233,
      },
      {
        namaIndo: "Ashilla Nawal Sakhi",
        namaArab: "أسيلا نوال ساخي",
        kelas: "Ruqayyah",
        induk: 20210205,
      },
      {
        namaIndo: "Athaya Malika Putri",
        namaArab: "أتايا مالكة فوتري",
        kelas: "Ruqayyah",
        induk: 20210207,
      },
      {
        namaIndo: "Hilwa Nadhifa El Fahmi",
        namaArab: "حلوى نظيفة الفهمي",
        kelas: "Ruqayyah",
        induk: 20210216,
      },
      {
        namaIndo: "Kanaya Raihanan Herbanu",
        namaArab: "كنايا ريحانان هيربانو",
        kelas: "Ruqayyah",
        induk: 20210218,
      },
      {
        namaIndo: "Khodijah Hasna",
        namaArab: "خديجة حسنى",
        kelas: "Ruqayyah",
        induk: 20210220,
      },
      {
        namaIndo: "Manaar Mohammed Hussein Al Gailani",
        namaArab: "منار محمد الجيلاني",
        kelas: "Ruqayyah",
        induk: 22230379,
      },
      {
        namaIndo: "Nayfa Aqila Nurdiawan",
        namaArab: "نايفة عاقلة نوردياوان",
        kelas: "Ruqayyah",
        induk: 20210235,
      },
      {
        namaIndo: "Nazwa Ghaziya El Syahinduka",
        namaArab: "نزوى غازية الشهيدة",
        kelas: "Ruqayyah",
        induk: 20210236,
      },
      {
        namaIndo: "Raihanna Jasmine Pinkan",
        namaArab: "ريحانة جاسمين بينكان",
        kelas: "Ruqayyah",
        induk: 20210237,
      },
      {
        namaIndo: "Shazia Aisyah Ilvi",
        namaArab: "شازيا عائشة إلفي",
        kelas: "Ruqayyah",
        induk: 20210239,
      },
      {
        namaIndo: "Syarifah Sarah",
        namaArab: "شريفة سارة",
        kelas: "Ruqayyah",
        induk: 19200240,
      },
      {
        namaIndo: "Abdurrohman Hanif Subhan",
        kelas: "Sa'ad",
        induk: 20210197,
      },
      {
        namaIndo: "Adam Al Ruzain",
        kelas: "Sa'ad",
        induk: 20210198,
      },
      {
        namaIndo: "Aditya Naufal Zaenaldi",
        kelas: "Sa'ad",
        induk: 20210200,
      },
      {
        namaIndo: "Alkhalifi Ammar Kuncoro",
        kelas: "Sa'ad",
        induk: 20210203,
      },
      {
        namaIndo: "Athaya Zain Al Ghazali",
        kelas: "Sa'ad",
        induk: 20210208,
      },
      {
        namaIndo: "Muhammad Abinduk Affan Sinaga",
        kelas: "Sa'ad",
        induk: 20210222,
      },
      {
        namaIndo: "Muhammad Al Fatih Mardiyanto",
        kelas: "Sa'ad",
        induk: 20210224,
      },
      {
        namaIndo: "Muhammad Azzam Al Fatih",
        kelas: "Sa'ad",
        induk: 20210227,
      },
      {
        namaIndo: "Muhammad Nashiruddin Al Hafindukzh",
        kelas: "Sa'ad",
        induk: 20210231,
      },
      {
        namaIndo: "Yazinduk Lutfi Ibrahim",
        kelas: "Sa'ad",
        induk: 20210242,
      },
      {
        namaIndo: "Adeeba Mahira Byhaqi",
        namaArab: "أديبة ماهرة بيهقي",
        kelas: "Ummu Kultsum",
        induk: 20210199,
      },
      {
        namaIndo: "Ardini Namiah Kirana",
        namaArab: "أرديني نامية كرانا",
        kelas: "Ummu Kultsum",
        induk: 20210204,
      },
      {
        namaIndo: "Auliya Izza Tunnisa",
        namaArab: "أولياء عزة تونيسا",
        kelas: "Ummu Kultsum",
        induk: 20210209,
      },
      {
        namaIndo: "Ayu Raline Adzkia",
        namaArab: "أيو رالين أذكياء",
        kelas: "Ummu Kultsum",
        induk: 20210210,
      },
      {
        namaIndo: "Dzafira Naila Abindukah",
        namaArab: "ظفيرة نائلة عابدة",
        kelas: "Ummu Kultsum",
        induk: 20210212,
      },
      {
        namaIndo: "Gainduka Hasna Syarif",
        namaArab: "غيداء حسناء شريف",
        kelas: "Ummu Kultsum",
        induk: 20210214,
      },
      {
        namaIndo: "Hanina Ninduka Ma'wa",
        namaArab: "حنين نداء مأوى",
        kelas: "Ummu Kultsum",
        induk: 20210215,
      },
      {
        namaIndo: "Mazaya Adhwa Asyura",
        namaArab: "مزايا أضواء عاشوراء",
        kelas: "Ummu Kultsum",
        induk: 20210221,
      },
      {
        namaIndo: "Nadia Agung Nurfadilah",
        namaArab: "نديا أغونج نور فضيلة",
        kelas: "Ummu Kultsum",
        induk: 20210234,
      },
      {
        namaIndo: "Tutupolij Nadhaqila Aliyya Zahra",
        namaArab: "توتوبوليج ناداقيلا عالية زهراء",
        kelas: "Ummu Kultsum",
        induk: 20210241,
      },
      {
        namaIndo: "Aisha Almahyra Nicky",
        namaArab: "عائشة الماهرة نيكي",
        kelas: "Maimunah",
        induk: 19200154,
      },
      {
        namaIndo: "Aisyah Jelita Permatasari",
        namaArab: "عائشة جيليتا برماتاساري",
        kelas: "Maimunah",
        induk: 18190140,
      },
      {
        namaIndo: "Ghaziyah Tsabita Assyarif",
        namaArab: "غازية ثابتة الشريف",
        kelas: "Maimunah",
        induk: 19200165,
      },
      {
        namaIndo: "Haninda Indraini",
        namaArab: "حنيندا إندريني",
        kelas: "Maimunah",
        induk: 19200167,
      },
      {
        namaIndo: "Khansa Rizq Khairunnisa",
        namaArab: "خنسا رزق خير النساء",
        kelas: "Maimunah",
        induk: 19200171,
      },
      {
        namaIndo: "Rayya Rufaindukah",
        namaArab: "رايا رفيدة ",
        kelas: "Maimunah",
        induk: 19200183,
      },
      {
        namaIndo: "Tasika Kinza Iskandar",
        namaArab: "تاسيكا كينزا إسكندر",
        kelas: "Maimunah",
        induk: 19200186,
      },
      {
        namaIndo: "Zhafiraah Akhayla Edgina Putri",
        namaArab: "زفيرة أكيلى بوتري",
        kelas: "Maimunah",
        induk: 19200188,
      },
      {
        namaIndo: "Zia Aqeela",
        namaArab: "زياء عاقلة",
        kelas: "Maimunah",
        induk: 19200190,
      },
      {
        namaIndo: "Afiqah Humairah Putrizaliyah",
        namaArab: "عفيقة حميراء بوتريزالية",
        kelas: "Maryam",
        induk: 19200150,
      },
      {
        namaIndo: "Afiqah Raihana Syuwanda",
        namaArab: "عفيقة ريحانة شوندى",
        kelas: "Maryam",
        induk: 19200151,
      },
      {
        namaIndo: "Aina Al Mardhiyah",
        namaArab: "عيناء المرضية",
        kelas: "Maryam",
        induk: 19200153,
      },
      {
        namaIndo: "Aisha Mikhayla Azzahra",
        namaArab: "عائشة ميكيلا الزهرة",
        kelas: "Maryam",
        induk: 19200155,
      },
      {
        namaIndo: "Farah Nadiyya Adam",
        namaArab: "فرح ناديا آدم  ",
        kelas: "Maryam",
        induk: 19200161,
      },
      {
        namaIndo: "Fathizza Madina Alzena",
        namaArab: "فاتزّا مدينا ألزينا",
        kelas: "Maryam",
        induk: 19200162,
      },
      {
        namaIndo: "Fayza Qairina Uzma",
        namaArab: "فائزة قيرنا عزمى",
        kelas: "Maryam",
        induk: 19200164,
      },
      {
        namaIndo: "Hafsa Moira Ghani",
        namaArab: "حفصة مويرا غاني",
        kelas: "Maryam",
        induk: 19200169,
      },
      {
        namaIndo: "Mikayla Darena Aneeqa",
        namaArab: "ميكيلا درينا أنيقة",
        kelas: "Maryam",
        induk: 19200174,
      },
      {
        namaIndo: "Nada Izzati El Islami",
        namaArab: "ندى عزتي الإسلامي",
        kelas: "Maryam",
        induk: 19200182,
      },
      {
        namaIndo: "Adzikro Genio Putra Wicaksono",
        kelas: "Thalhah",
        induk: 19200149,
      },
      {
        namaIndo: "Ahmad Alwan Ayyasy",
        kelas: "Thalhah",
        induk: 19200152,
      },
      {
        namaIndo: "Bryan Alvaro Eshan Lim",
        kelas: "Thalhah",
        induk: 19200157,
      },
      {
        namaIndo: "Dawud Muhammad Fawwaz",
        kelas: "Thalhah",
        induk: 19200159,
      },
      {
        namaIndo: "Fatih Rahman Karim",
        kelas: "Thalhah",
        induk: 19200163,
      },
      {
        namaIndo: "Khaled Waleed Obainduk Adam Hamna",
        kelas: "Thalhah",
        induk: 22230416,
      },
      {
        namaIndo: "Muhammad Alzam Hafiz Masykuri",
        kelas: "Thalhah",
        induk: 19200175,
      },
      {
        namaIndo: "Muhammad Ghailan Althaf",
        kelas: "Thalhah",
        induk: 19200177,
      },
      {
        namaIndo: "Muhammad Ghifari Ar Rashdan",
        kelas: "Thalhah",
        induk: 19200178,
      },
      {
        namaIndo: "Wafi Abiyu Ard Suryanto",
        kelas: "Thalhah",
        induk: 19200187,
      },
      {
        namaIndo: "Abdurrahman Hafeez Amini",
        kelas: "Zubair",
        induk: 19200147,
      },
      {
        namaIndo: "Abiyya Sonofaira Abdurrauf",
        kelas: "Zubair",
        induk: 19200148,
      },
      {
        namaIndo: "Azka Naufal Ramadhan",
        kelas: "Zubair",
        induk: 19200191,
      },
      {
        namaIndo: "Dzikra Raif Ghanim",
        kelas: "Zubair",
        induk: 19200160,
      },
      {
        namaIndo: "Ibrahim Rumi Aditya",
        kelas: "Zubair",
        induk: 19200168,
      },
      {
        namaIndo: "Keenan Nakhla Adinata",
        kelas: "Zubair",
        induk: 19200170,
      },
      {
        namaIndo: "Muhammad Faqihuddin Pallawagau Zuljazmy S.",
        kelas: "Zubair",
        induk: 19200172,
      },
      {
        namaIndo: "Muhammad Firzan Keandra Hendri",
        kelas: "Zubair",
        induk: 19200176,
      },
      {
        namaIndo: "Rayyan Akmalzaky Inada",
        kelas: "Zubair",
        induk: 19200184,
      },
      {
        namaIndo: "Riza Dwiputra Fahrizi",
        kelas: "Zubair",
        induk: 19200185,
      },
      {
        namaIndo: "Afnan Osama Mohammad Gareba",
        namaArab: "أفنان أسامة محمد غريبة",
        kelas: "Asma'",
        induk: 19200192,
      },
      {
        namaIndo: "Ahira Filza Mumtaza",
        namaArab: "أهيرا فيليزا ممتازة",
        kelas: "Asma'",
        induk: 18190132,
      },
      {
        namaIndo: "Aisyah Fahad Alamudy",
        namaArab: "عائشة فهد العمودي",
        kelas: "Asma'",
        induk: 18190129,
      },
      {
        namaIndo: "Aisyah Juwita Permatasari",
        namaArab: "عائشة جويتا برماتا ساري",
        kelas: "Asma'",
        induk: 18190139,
      },
      {
        namaIndo: "Alesya Ferilyan Buzaar",
        namaArab: "أليشا فريليان بُزار",
        kelas: "Asma'",
        induk: 18190121,
      },
      {
        namaIndo: "Chesyl Aulia Akhmad",
        namaArab: "جيشيل أولياء أحمد",
        kelas: "Asma'",
        induk: 18190113,
      },
      {
        namaIndo: "Fatimah Ayna Qolbi",
        namaArab: "فاطمة عين قلبي",
        kelas: "Asma'",
        induk: 18190124,
      },
      {
        namaIndo: "Feliz Aneesa Fareza",
        namaArab: "فيليس أنيسا فاريزا",
        kelas: "Asma'",
        induk: 18190109,
      },
      {
        namaIndo: "Keyla Sabiya Al Aura",
        namaArab: "كيلا سابيا العورى",
        kelas: "Asma'",
        induk: 18190137,
      },
      {
        namaIndo: "Kiandra Ayla Fazia",
        namaArab: "كيندارا أيلا فازيا",
        kelas: "Asma'",
        induk: 18190116,
      },
      {
        namaIndo: "Lathifah Syahmi",
        namaArab: "لطيفة شهمي",
        kelas: "Asma'",
        induk: 18190143,
      },
      {
        namaIndo: "Mazaya Qanita",
        namaArab: "مزايا قانتة",
        kelas: "Asma'",
        induk: 18190141,
      },
      {
        namaIndo: "Nadira Zahra Amini",
        namaArab: "ناضرة زهرى أميني",
        kelas: "Asma'",
        induk: 18190111,
      },
      {
        namaIndo: "Nadria Mandalika",
        namaArab: "ندريا ماندالك",
        kelas: "Asma'",
        induk: 18190136,
      },
      {
        namaIndo: "Naura Bilqis Ayesha",
        namaArab: "نَوْرا بلقس أييشا",
        kelas: "Asma'",
        induk: 18190134,
      },
      {
        namaIndo: "Raisva Malika Putri",
        namaArab: "ريسْفا ماليكا بوتري",
        kelas: "Asma'",
        induk: 18190120,
      },
      {
        namaIndo: "Rhanaya Azzahra Prasetiyo",
        namaArab: "رانايا الزهرة براستيو",
        kelas: "Asma'",
        induk: 18190123,
      },
      {
        namaIndo: "Syarifah Najwa",
        namaArab: "شريفة نجوى",
        kelas: "Asma'",
        induk: 18190106,
      },
      {
        namaIndo: "Ahmad Azzam Ash Shindukdiq",
        namaArab: "أحمد عزام الصديق\r\n",
        kelas: "Muadz",
        induk: 18190118,
      },
      {
        namaIndo: "Ala Haindukar",
        namaArab: "علاء حيدر",
        kelas: "Muadz",
        induk: 18190130,
      },
      {
        namaIndo: "Alifiandra Hafindukz Thala",
        namaArab: "أليفياندرا حافظ تلا\r\n",
        kelas: "Muadz",
        induk: 18190117,
      },
      {
        namaIndo: "Andi M Arafat Atharizz",
        namaArab: "أندي محمد عرفات التاريز",
        kelas: "Muadz",
        induk: 18190115,
      },
      {
        namaIndo: "Darvish Reza Alfaiz",
        namaArab: "درفيش ريزا الفائز",
        kelas: "Muadz",
        induk: 18190114,
      },
      {
        namaIndo: "Davaqeela Khalfanizza Yolando Putra",
        namaArab: "دفاقيلا كلفانزّا يولندو بوترا",
        kelas: "Muadz",
        induk: 18190142,
      },
      {
        namaIndo: "Farel Prayata Admaja",
        namaArab: "فاريل بَراياتا أتماجا",
        kelas: "Muadz",
        induk: 18190127,
      },
      {
        namaIndo: "Ibrahim Nesar Al Fathin",
        namaArab: "إبراهيم نيسار الفاطن\r\n",
        kelas: "Muadz",
        induk: 18190110,
      },
      {
        namaIndo: "Ken Kaisan Ramadhani",
        namaArab: "كين كيسان رمضان\r\n",
        kelas: "Muadz",
        induk: 18190131,
      },
      {
        namaIndo: "Muhammad Aryasa Zefa",
        namaArab: "محمد أرْياسا زيفا",
        kelas: "Muadz",
        induk: 18190122,
      },
      {
        namaIndo: "Muhammad Ghazi Putra A",
        namaArab: "محمد غازي بوترا\r\n",
        kelas: "Muadz",
        induk: 18190119,
      },
      {
        namaIndo: "Muhammad Ibadurohman Maqbul",
        namaArab: "محمد عباد الرحمن مقبول",
        kelas: "Muadz",
        induk: 18190128,
      },
      {
        namaIndo: "Muhammad Rezvanda Zavier Adam",
        namaArab: "محمد ريزْفندا زافير آدم\r\n",
        kelas: "Muadz",
        induk: 18190135,
      },
      {
        namaIndo: "Nur Hindukayat Setiadi Putra",
        namaArab: "نور هدايات ستيادي بوترا",
        kelas: "Muadz",
        induk: 18190112,
      },
      {
        namaIndo: "Rasyinduk Rafi Muhammad",
        namaArab: "رشيد رافي محمد",
        kelas: "Muadz",
        induk: 18190126,
      },
      {
        namaIndo: "Sean Ibrahim Sattar El-kindy",
        namaArab: "سيان إبراهيم ستار الكندي",
        kelas: "Muadz",
        induk: 18190125,
      },
      {
        namaIndo: "Aisyah Febby Sari Ramadhani",
        kelas: "Khansa'",
        induk: 17180084,
      },
      {
        namaIndo: "Almira Mahrin Hafiza",
        kelas: "Khansa'",
        induk: 17180082,
      },
      {
        namaIndo: "Indira Magali",
        kelas: "Khansa'",
        induk: 17180073,
      },
      {
        namaIndo: "Najma Aqila Mahya",
        kelas: "Khansa'",
        induk: 17180074,
      },
      {
        namaIndo: "Abdullah Farih Waffa",
        kelas: "Mush'ab",
        induk: 17180066,
      },
      {
        namaIndo: "Bima Satria Hindukayat",
        kelas: "Mush'ab",
        induk: 17180094,
      },
      {
        namaIndo: "Farrel Athanny Abdurachman",
        kelas: "Mush'ab",
        induk: 17180101,
      },
      {
        namaIndo: "El Azka Ghalibie",
        kelas: "Khalinduk",
        induk: 22230359,
      },
      {
        namaIndo: "Mohammed Osama Mohammad Gareba",
        kelas: "Khalinduk",
        induk: 19200193,
      },
      {
        namaIndo: "Nararya Haydar",
        kelas: "Khalinduk",
        induk: 22230370,
      },
      {
        namaIndo: "Aleyya Mazaya Aditya",
        kelas: "Ummu Salamah",
        induk: 16170044,
      },
      {
        namaIndo: "Alya Namara Putri Maulinduka",
        kelas: "Ummu Salamah",
        induk: 22230341,
      },
      {
        namaIndo: "Balqis Syarifah Fathin",
        kelas: "Ummu Salamah",
        induk: 16170033,
      },
      {
        namaIndo: "Mahasin Asiyah",
        kelas: "Ummu Salamah",
        induk: 18190105,
      },
      {
        namaIndo: "Namiyah Ersalan Ambadar",
        kelas: "Ummu Salamah",
        induk: 22230343,
      },
      {
        namaIndo: "Nasywa Aliyah Ilmi",
        kelas: "Ummu Salamah",
        induk: 22230344,
      },
      {
        namaIndo: "Naura Hasna Salsabila Rahardjo",
        kelas: "Ummu Salamah",
        induk: 22230345,
      },
      {
        namaIndo: "Rania Rahima Malay",
        kelas: "Ummu Salamah",
        induk: 22230346,
      },
      {
        namaIndo: "Salis Sahla Aziza",
        kelas: "Ummu Salamah",
        induk: 16170034,
      },
      {
        namaIndo: "Zalfa Nabila Putri Wicaksono",
        kelas: "Ummu Salamah",
        induk: 22230347,
      },
      {
        namaIndo: "Abdullah Fahmi Barindukwan",
        kelas: "Bilal",
        induk: 15160012,
      },
      {
        namaIndo: "Abdullah Haindukar",
        kelas: "Bilal",
        induk: 15160023,
      },
      {
        namaIndo: "Alfath Raya Akwila",
        kelas: "Bilal",
        induk: 21220301,
      },
      {
        namaIndo: "Bilal Sahnon",
        kelas: "Bilal",
        induk: 21220303,
      },
      {
        namaIndo: "Darrio Aryabani Safar",
        kelas: "Bilal",
        induk: 15160020,
      },
      {
        namaIndo: "Hayder Rahman Hatim",
        kelas: "Bilal",
        induk: 15160017,
      },
      {
        namaIndo: "Rafif Safa Abiyu Abdurrauf",
        kelas: "Bilal",
        induk: 21220306,
      },
      {
        namaIndo: "Syarif Abu Bakar Adeni Alqadrie",
        kelas: "Bilal",
        induk: 21220309,
      },
      {
        namaIndo: "Al Madina Jasmine",
        kelas: "Sarah",
        induk: 21220300,
      },
      {
        namaIndo: "Alifa Kineta Kanza",
        kelas: "Sarah",
        induk: 21220302,
      },
      {
        namaIndo: "Berthlinale Mehrunnisa Radhiya",
        kelas: "Sarah",
        induk: 22230378,
      },
      {
        namaIndo: "Joyce Ghanima Petriviena",
        kelas: "Sarah",
        induk: 21220304,
      },
      {
        namaIndo: "Nabila Azka Hendari",
        kelas: "Sarah",
        induk: 21220305,
      },
      {
        namaIndo: "Sawsan Hasna Aqila Ayesha",
        kelas: "Sarah",
        induk: 21220307,
      },
      {
        namaIndo: "Shahira Kamilia Adani",
        kelas: "Sarah",
        induk: 21220308,
      },
      {
        namaIndo: "Zharifah Zora Almira",
        kelas: "Sarah",
        induk: 21220310,
      },
    ],
  });
}
