version: "3.8"
services:
  raporDb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - letsencrypt-docker-compose_default

# change port in prod ex: 5432:5432 to 5432 only
# enable this in prod
networks:
  letsencrypt-docker-compose_default:
    external: true
