version: "3.8"
services:
  raporDb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./postgres:/var/lib/postgresql/data
